### ISSUE TITLE
BPF testcases fail due to a bug in PyVEX

### ISSUE THREAD

**Issue by zardus** [angr/angr-platforms#13]
It looks like BPF support bitrotted between the PR being opened and the PR being merged in. @subwire or @fish, could you take a look?

**Comment by subwire** [comment]
I actually successfully ran the tests before merging.  Hmm...

**Comment by ltfish** [comment]
I figured out what is going on. Here is the chat log copied from the angr core channel:

---

fish [1:50 AM] 
@lockshaw @subwire
in `pyvex/lift/__init__.py:lift()`
```    for lifter in lifters:
            ....
            next_irsb_part = lifter(arch, addr)._lift(u_data, bytes_offset, max_bytes, max_inst, opt_level, traceflags, allow_lookback)
```
this is not ideal, since sometimes we have more than one lifters registered (apart from the default VEX lifter), and it's possible that the both lifters are able to lift that instruction


[1:51] 
this is exactly why test cases on travis CI is failing: both BPF and MSP430 lifters are currently registered in the CI, and the MSP430 lifter is called first and tries to lift a BPF instruction


[1:55] 
here is the old way:
```    for lifter, registered_arch in lifters:
        if not isinstance(arch, registered_arch):
            continue
```
I think the old way is better - we don't accidentally use lifters for one architecture to lift blocks in another architecture


[1:56] 
Here is my proposal: we keep a dict that maps each supported architecture to a list of lifters, which will allow us to do the following:
```for lifter in arch_lifters[arch.name]:
   ....
```
what do you think?

---

**Comment by ltfish** [comment]
The related PyVEX commit: https://github.com/angr/pyvex/commit/e47ca1b5

**Comment by ltfish** [comment]
To reproduce the issue locally: Add the following line at the beginning of `test_bpf_idea.py`, right after `import angr`:

```
from angr_platforms.msp430 import *
```

**Comment by subwire** [comment]
Now this explains everything.
Yeah, let's add the arch, that makes perfect sense.
